import gql from 'graphql-tag'
import Head from 'next/head'
import Image from 'next/image'
import { useQuery } from '@apollo/client'
import { initializeApollo } from '../apollo/client'
import styles from '../../styles/Home.module.css'
import { useState, useCallback } from 'react'
import { useRouter } from 'next/router'

const Index = () => {
  const router = useRouter()
  const currentPage = router.query

  const [books, setBooks] = useState([])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div>
            <ul>
                {/* {
                  books && books.length > 0 && books.map((book, index) => (
                    <li key={index}>{book.title}</li>
                  ))
                } */}
            </ul>
            <button onClick={() => {
              let offset
              if (currentPage && currentPage.page) {
                offset = Number(currentPage.page) - 10
              } else {
                offset = 0
              }
              router.push(`?page=${offset}`)
            }}>
              Previous
              </button>
            <button onClick={() => {
              let offset
              if (currentPage && currentPage.page) {
                offset = Number(currentPage.page) + 10
              } else {
                offset = 10
              }
              router.push(`?page=${offset}`)
            }}>
              Next
            </button>
        </div>
        </div>
      </main>
    </div>
  )
}
export default Index
